config/routes.rb
Rails.application.routes.draw do
  root 'student_sessions#index'
  resources :student_sessions, except: :show
  resources :students, except: :show
  resources :sessions, except: :show

  get 'instructor' => 'instructor#dashboard', as: :instructor

end

app/models/session.rb
class Session < ActiveRecord::Base
  has_many :student_sessions, dependent: :destroy
  has_many :students, :through => :student_sessions

  default_scope { order('date ASC') }
  scope :upcoming, -> { where('date >= ?', (Time.now - 28.hours)) }

  def price_range
    total_sessions = self.student_sessions.count
    return "$" + (135.0/total_sessions).ceil.to_s
  end
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :student_sessions, dependent: :destroy
  has_many :sessions, :through => :student_sessions

  default_scope { order('name ASC') }
end

app/models/student_session.rb
class StudentSession < ActiveRecord::Base
  belongs_to :student
  belongs_to :session
  validates :student, :presence => { :message => 'Student cannot be blank, submission not saved' }
  validates :session, :presence => { :message => 'Class cannot be blank, submission not saved' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/instructor_controller.rb
class InstructorController < ApplicationController

  def dashboard
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :set_session, only: [:edit, :update, :destroy]

  # GET /sessions
  # GET /sessions.json
  def index
    @sessions = Session.all
  end

  # GET /sessions/new
  def new
    @session = Session.new
  end

  # GET /sessions/1/edit
  def edit
  end

  # POST /sessions
  # POST /sessions.json
  def create
    @session = Session.new(session_params)

    respond_to do |format|
      if @session.save
        format.html { redirect_to sessions_path, notice: 'Session was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /sessions/1
  # PATCH/PUT /sessions/1.json
  def update
    respond_to do |format|
      if @session.update(session_params)
        format.html { redirect_to sessions_path, notice: 'Session was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /sessions/1
  # DELETE /sessions/1.json
  def destroy
    @session.destroy
    respond_to do |format|
      format.html { redirect_to sessions_url, notice: 'Session was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_session
      @session = Session.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def session_params
      params.require(:session).permit(:date)
    end
end

app/controllers/student_sessions_controller.rb
class StudentSessionsController < ApplicationController
  before_action :set_student_session, only: [:show, :edit, :update, :destroy]

  # GET /student_sessions
  # GET /student_sessions.json
  def index
    @student_sessions = StudentSession.all
    @sessions = Session.all
  end

  # GET /student_sessions/new
  def new
    @student_session = StudentSession.new
  end

  # GET /student_sessions/1/edit
  def edit
  end

  # POST /student_sessions
  # POST /student_sessions.json
  def create
    @student_session = StudentSession.new(student_session_params)

    respond_to do |format|
      if @student_session.save
        format.html { redirect_to student_sessions_path, notice: 'You successfully signed up!' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /student_sessions/1
  # PATCH/PUT /student_sessions/1.json
  def update
    respond_to do |format|
      if @student_session.update(student_session_params)
        format.html { redirect_to student_sessions_path, notice: 'Student session was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /student_sessions/1
  # DELETE /student_sessions/1.json
  def destroy
    @student_session.destroy
    respond_to do |format|
      format.html { redirect_to student_sessions_url, notice: 'Class participation canceled.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_session
      @student_session = StudentSession.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_session_params
      params.require(:student_session).permit(:student_id, :session_id, :certainty)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to students_path, notice: 'Student was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to students_path, notice: 'Student was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/student_sessions_helper.rb
module StudentSessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/instructor/dashboard.erb
<h1>Instructor Dashboard</h1>

<%= link_to 'All Students', students_path %>
<br>
<%= link_to 'All Class Dates', sessions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ballet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/student_sessions/_form.html.erb
<%= form_for(@student_session) do |f| %>
  <% if @student_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student_session.errors.count, "error") %> prohibited this student_session from being saved:</h2>

      <ul>
      <% @student_session.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>If you are not on the list of students, contact Desiré to add you to the app.</p>

  <div class="field form-group">
    <%= f.label :student_id, :class => "col-lg-2 control-label"  %><br>
    <%= f.select :student_id, Student.all.collect {|s| [ s.name, s.id ] }, {:prompt => "Select Student"}, { :class => "form-control" } %>
  </div>
  <div class="field form-group">
    <%= f.label "Class", :class => "col-lg-2 control-label" %><br>
    <%= f.select :session_id, Session.upcoming.collect {|s| [ s.date.strftime("%m/%d/%Y"), s.id ] }, {}, { :class => "form-control" } %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", :class => "btn btn-primary btn-raised"%>
  </div>
<% end %>

app/views/student_sessions/edit.html.erb
<h1>Editing student_session</h1>

<%= render 'form' %>

<%= link_to 'Show', @student_session %> |
<%= link_to 'Back', student_sessions_path %>

app/views/student_sessions/index.html.erb
<div id="roster">
  <h1 class="navbar navbar-default">Friday Night Ballet Roster</h1>

  <h2>How the classes work:</h2>
  <p>1.5 hours</p>
  <p>$135 - divided by number of students</p>
  <p>48 hour cancellation policy</p>

  <br>

  <div id="notice" class="alert alert-dismissable alert-success"><%= notice %></div>

  <h1>Upcoming Classes</h2>

  <%= link_to 'Sign Up for a class!', new_student_session_path, :class => "btn btn-primary btn-raised" %>

  <br>
  <br>
  <br>

  <% @sessions.each do |session| %>
    <% if session.date >= (Time.now - 28.hours)%>
      <h2><%= session.date.strftime("%m/%d/%Y") %></h2>
      <% if session.student_sessions.count < 1 %>
        <p class="text-info">No one is signed up yet!</p>
      <% else %>
        <h4>Estimated Cost: <%= session.price_range %></h4>
        <% session.student_sessions.each do |ss| %>
          <p>
            <%= ss.student.name if ss.student %>
            <%= link_to 'Edit', edit_student_session_path(ss) %>
            <%= link_to 'X', ss, method: :delete, data: { confirm: 'Are you sure you want to cancel?' } %>
          </p>
        <% end %>
      <% end %>
      <hr>
    <% end %>
  <% end %>

  <br>

  <h1>Past Classes</h2>
  <% @sessions.each do |session| %>
    <% if (session.date < (Time.now - 28.hours)) && (session.student_sessions.count > 0) %>
      <h2><%= session.date.strftime("%m/%d/%Y") %></h2>
      <% session.student_sessions.each do |ss| %>
        <p><%= ss.student.name %></p>
      <% end %>
    <% end %>
  <% end %>

</div>

app/views/student_sessions/new.html.erb
<div id="sign-up">
  <h1 class="navbar navbar-default">Sign Up for a Class</h1>

  <%= render 'form' %>

  <%= link_to 'Back to Roster', student_sessions_path %>
</div>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-primary btn-raised" %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1 class="navbar navbar-default">Edit Student Name</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1 class="navbar navbar-default">All Students</h1>

    <% @students.each do |student| %>
        <p><%= student.name %>
        <%= link_to 'Edit', edit_student_path(student) %>
        <%= link_to 'X', student, method: :delete, data: { confirm: 'Are you sure?' } %></p>
    <% end %>

<br>

<%= link_to 'Add New Student', new_student_path %>
<br>
<%= link_to 'Back to Instructor Dashboard', instructor_path %>

app/views/students/new.html.erb
<h1 class="navbar navbar-default">New Student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>